name: Build and Push Docker Image with Semantic Versioning

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  check_merge_condition:
    runs-on: ubuntu-latest
    outputs:
      should_proceed: ${{ steps.check.outputs.should_proceed }}
    steps:
      - name: Check if PR was merged from development
        id: check
        run: |
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"

          if [[ "${{ github.event.pull_request.merged }}" == "true" && "${{ github.event.pull_request.head.ref }}" == "development" ]]; then
            echo "should_proceed=true" >> $GITHUB_OUTPUT
          else
            echo "should_proceed=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: check_merge_condition
    if: needs.check_merge_condition.outputs.should_proceed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest tag from Docker Hub
        id: latest_tag
        run: |
          tags=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/silent-log-agent/tags?page_size=100" | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)

          latest=$(echo "$tags" | tail -n 1)
          if [[ -z "$latest" ]]; then
            latest="v1.0.0"
          else
            major=$(echo $latest | cut -d. -f1 | tr -d 'v')
            minor=$(echo $latest | cut -d. -f2)
            patch=$(echo $latest | cut -d. -f3)

            patch=$((patch + 1))
            if [ $patch -gt 9 ]; then
              patch=0
              minor=$((minor + 1))
            fi

            if [ $minor -gt 9 ]; then
              minor=0
              major=$((major + 1))
            fi

            latest="v$major.$minor.$patch"
          fi

          echo "new_tag=$latest" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/silent-log-agent:${{ steps.latest_tag.outputs.new_tag }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/silent-log-agent:latest .

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/silent-log-agent:${{ steps.latest_tag.outputs.new_tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/silent-log-agent:latest

      - name: Push Git Tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ steps.latest_tag.outputs.new_tag }}
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin ${{ steps.latest_tag.outputs.new_tag }}